# ln -s ~/ca/survos/packages/api-grid-bundle/assets/src/controllers/sandbox_api_grid_controller.js assets/controllers/sandbox_api_grid_controller.js
# ln -s ~/g/survos/survos/packages/api-grid-bundle/assets/src/controllers/sandbox_api_grid_controller.js assets/controllers/sandbox_api_grid_controller.js
survos_api_grid:
  meiliHost: '%env(MEILI_SERVER)%'
  meiliKey: '%env(MEILI_API_KEY)%'

when@dev:
  survos_api_grid:
#    stimulus_controller: sandbox_api_grid


